[package]
name = "grain_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
audiorust = { path = "../audiorust" }
glob = "0.3.1"
rand = "0.8.5"
rusqlite = {version = "0.31.0", features = ["bundled"]}
